version: "3"

services:
  bot:
    container_name: bot
    build: .
    env_file:
      - docker.env
    networks:
      - bot

  mongo:
    container_name: bot-mongo
    image: mongo:5.0-rc-focal
    ports:
      - "27017:27017"
    env_file:
      - docker.env
    networks:
      - bot

  parser:
    container_name: bot-parser
    image: ${PARSER_IMAGE}
    env_file:
      - docker.env
    ports:
      - "8000:8000"
    networks:
      - bot

  tokenparser:
    container_name: bot-token
    image: ${TOKENPARSER_IMAGE}
    networks:
      - bot

  redis:
    container_name: bot-redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - bot

networks:
  bot:
    driver: bridge
