version: "3"

services:
  bot:
    container_name: bot
    image: ${BOT_REGISTRY}/${BOT_IMAGE}:${BOT_TAG}
    restart: always
    depends_on:
      mongo:
        condition: service_started
    volumes:
      - ./logs:/logs
    env_file:
      - .env
    networks:
      - bot

  mongo:
    container_name: bot-mongo
    image: mongo:5.0-rc-focal
    volumes:
      - ./dbdata:/data/db
    env_file:
      - .env
    networks:
      - bot

  parser:
    container_name: bot-parser
    image: ${PARSER_IMAGE}
    env_file:
      - .env
    volumes:
      - ./logs/parser:/logs
    networks:
      - bot

  redis:
    container_name: bot-redis
    image: redis:latest
    restart: always
    volumes:
      - ./redis_data:/data
    networks:
      - bot

  nginx:
    container_name: bot-nginx
    image: nginx:alpine
    restart: always
    depends_on:
      bot:
        condition: service_started
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./geo.conf:/etc/nginx/geo.conf
      - ./logs/nginx:/var/log/nginx
      - ${NGINX_CERT}:/etc/nginx/certs/cert.pem
      - ${NGINX_KEY}:/etc/nginx/certs/privkey.pem
    networks:
      - bot

networks:
  bot:
    driver: bridge
