version: "3"

services:
  bot:
    container_name: bot
    image: ${BOT_REGISTRY}/${BOT_IMAGE}:${BOT_TAG}
    restart: always
    depends_on:
      mongo:
        condition: service_started
    volumes:
      - ./logs:/logs
      - ${MONGO_CERTS}:/certs/mongodb
    env_file:
      - .env
    networks:
      - bot

  mongo:
    container_name: bot-mongo
    image: mongo:5.0-rc-focal
    ports:
      - "27017:27017"
    volumes:
      - ./dbdata:/data/db
      - ./mongod.conf:/etc/mongod.conf
      - ${MONGO_CERTS}:/etc/ssl/mongo
    command: --config /etc/mongod.conf
    env_file:
      - .env
    networks:
      - bot

  selenium:
    container_name: bot-selenium
    image: selenium/standalone-chrome:latest
    deploy:
      resources:
        limits:
          memory: 1gb
    networks:
      - bot

  redis:
    container_name: bot-redis
    image: redis:latest
    restart: always
    networks:
      - bot

  nginx:
    container_name: bot-nginx
    image: nginx:alpine
    restart: always
    depends_on:
      bot:
        condition: service_started
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
      - ${NGINX_CERT}:/etc/nginx/certs/cert.pem
      - ${NGINX_KEY}:/etc/nginx/certs/privkey.pem
    networks:
      - bot

networks:
  bot:
    driver: bridge
