global:
  scrape_interval: 30s
  evaluation_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'bot'
    static_configs:
      - targets: ['bot:8082']

  - job_name: 'parser'
    static_configs:
      - targets: ['parser:8082']
