name: CI-prod

on:
  push:
    branches:
      - main

env:
  TEST_MONGO_CONTAINER: "test_mongo"
  TEST_REDIS_CONTAINER: "test_redis"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: install go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.0

      - name: checkout
        uses: actions/checkout@v4

      - name: create test db
        run: | 
          docker run --name $(echo TEST_MONGO_CONTAINER) --rm -d -p 27017:27017 mongo:5.0-rc-focal
          docker run --name $(echo TEST_REDIS_CONTAINER) --rm -d -p 6379:6379 redis:latest

      - name: run tests
        run: go test -v ./...

      - name: remove containers
        run: | 
          docker stop $(echo TEST_MONGO_CONTAINER)
          docker stop $(echo TEST_REDIS_CONTAINER)

  build_and_push:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.BOT_IMAGE }}

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - uses: actions/checkout@v4

      - name: update configuration via ssh
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "deploy/"
          target: ${{ secrets.WORKDIR }}
          strip_components: 1

      - name: deploy via ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ secrets.WORKDIR }}
            docker-compose stop bot nginx
            docker-compose rm -f bot
            docker-compose pull -q
            docker-compose up -d --force-recreate nginx